### ISSUE TITLE
Maps are order sensitive when using wildcards 

### ISSUE THREAD

**Issue by slifin** [hyperfiddle/rcf#52] opened 2022-04-13 10:27 UTC
```
(tests
  {:a "a" :b "b"} := {:b "b" :a "a"}
  {:a "a" :b "b"} := {:a "a" :b "b"}
  {:a "a" :b "b"} := {:b _ :a _}
  {:a "a" :b "b"} := {:a _ :b _})
```

```
❌
in {:a "a", :b "b"}

{:a "a", :b "b"}
:<>
{:b _, :a _}
```

I'm not sure if this is intended or not but this behavior can result in very brittle tests since maps are purely associative and order shouldn't be relied on by default

**Comment by dustingetz** [comment] 2022-04-13 13:11
Thank you Adrian
Duplicate of https://github.com/hyperfiddle/rcf/issues/48
Fixed in internal dev branch, technical alpha coming soon

**Closed** 2022-07-20 20:10 UTC
